#version 460 core
layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba8, binding = 0) uniform readonly image2D inputImage;
layout(rgba8, binding = 1) uniform writeonly image2D outputImage;
uniform float uTime;
float scale = 10;
float timeScale = 1;
vec2 Plasma_distortion(vec2 uv){
    vec2 scaled_uv = vec2(uv)*scale;
    float time = uTime * timeScale;
    float w1 = sin(scaled_uv.x + time);
    float w2 = sin(scaled_uv.y + time) + 0.5;
    float w3 = sin(scaled_uv.x + scaled_uv.y + time);
    float r = sin(sqrt(scaled_uv.x*scaled_uv.x+scaled_uv.y*scaled_uv.y)+time);
    float finalvalue = r+ w1 + w2 + w3;
    vec2 distortion = vec2(sin(finalvalue*3.1459), cos(finalvalue*3.1459))*0.1;
    return uv + distortion;
    }
ivec2 uvToP(vec2 uv, ivec2 size) {
    return ivec2(uv*vec2(size));
}
void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    if (p.x >= size.x || p.y >= size.y) return;

    vec2 uv = (vec2(p) + 0.5) / vec2(size);
    vec2 displaced_uv = Plasma_distortion(uv);
    displaced_uv = clamp(displaced_uv, vec2(0.0), vec2(1.0));
    ivec2 samplePos = uvToP(displaced_uv, size);
    samplePos = clamp(samplePos, ivec2(0), size - ivec2(1));
    vec4 color = imageLoad(inputImage, samplePos);
    imageStore(outputImage, p, color);
}
